#!/bin/bash

# Generate the list of combinations


#!/bin/bash

# Generate the list of combinations
combinations=(
    "1 2 3" "1 3 2" "2 1 3" "2 3 1" "3 1 2" "3 2 1"
)

# Loop through each combination
for index in "${!combinations[@]}"; do
    combination=${combinations[index]}

    # Execute Push_swap with the combination and store the output
    output=$(./Push_swap $combination)

    # Execute the checker and get the result
    result=$(echo "$output" | ./checker_Mac $combination)

    # Count the number of commands executed
    num_commands=$(echo "$output" | wc -l)

    # Print the result and number of commands
    echo "$result $num_commands"

    # Check if the result is KO and print the combination number
    if [[ $result == "KO" ]]; then
        echo "Combination number: $((index+1))"
    fi
done


